# Generated by Django 3.0.3 on 2020-05-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents_other_info',
            name='agent_img',
            field=models.CharField(default='中介图片', max_length=60),
        ),
    ]
