# Generated by Django 3.0.3 on 2021-03-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.IntegerField(default='中介ID')),
                ('agent_name', models.CharField(default='中介姓名', max_length=60)),
                ('agent_img', models.CharField(default='中介图片', max_length=60)),
                ('agent_url', models.CharField(default='中介个人主页', max_length=100)),
                ('original_avg_score', models.FloatField(default='原始评分均值')),
                ('emotion_avg_score', models.FloatField(default='评论文本情感得分均值')),
            ],
        ),
    ]
